# Generated by Django 6.1.1 on 2026-09-27 15:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Phone number must be 11 digits, starting with 090/091/080/081/070.', regex='^(090|091|080|081|070)\\d{8}$')]),
        ),
    ]
